spring.application.name=backend
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/weathero2_db
spring.datasource.username=postgres
spring.datasource.password=admin37
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.h2.console.enabled=true

server.port=8080

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.timeout=2000ms
spring.redis.jedis.pool.max-active=8
spring.redis.jedis.pool.max-idle=8
spring.redis.jedis.pool.min-idle=0

# Pollution API Configuration
pollution.api.openaq.url=https://api.openaq.org/v3
pollution.api.waqi.url=https://api.waqi.info
pollution.api.waqi.token=demo

# Weather API Configuration
weather.api.openmeteo.url=https://api.open-meteo.com
weather.api.openweather.url=https://api.openweathermap.org
weather.api.openweather.key=9ee8e061aed0e4f1cf991a11f8169fc1
weather.api.weatherapi.url =https://api.weatherapi.com/v1
weather.api.weatherapi.key=2f93772691384e65ac0115826252510
weather.api.tomorrow.url=https://api.tomorrow.io/v4
weather.api.tomorrow.key=d3CQ9UKGAI2N3FmQiSp02w12LbSylvLa


# Elevation API Configuration
elevation.api.url=https://api.open-elevation.com

# ML Service Configuration
ml.service.url=http://localhost:8000

# Upload Configuration
upload.local.path=./uploads

# Geocoding API Configuration
geocoding.api.url=https://geocoding-api.open-meteo.com/v1